# Day 2 ml

In [1]:
import numpy as np


### Create vector 

In [2]:
#load library
import numpy as np

#create a row vector 
row_vector=np.array([10,15,20])
print(row_vector)

##create a column vector 
col_vector=np.array([[10],[17],[20]])
print(col_vector)




[10 15 20]
[[10]
 [17]
 [20]]


####  Create a matrix

In [3]:
#create  a matrix 
matrix=np.array([[10,20,30],[40,50,60]])
print("the matrix is ",matrix)

the matrix is  [[10 20 30]
 [40 50 60]]


# Accessing Elements 

In [5]:
#create a row vector 
row_vector=np.array([10,15,20,45,34,23,1234])
print(row_vector)

#create  a matrix 
matrix = np.array([[10,20,30],[40,50,60],[34,45,67]])
print("the matrix is ",matrix)

#select the 2nd elememnt of vector 
print("row_vector[2] is ",row_vector[1])

#  SELECT THE 3RD ROW  AND 3RD COLUMN OF  THE MATRIX 
print("the 3rd  row and 3rd column is [2][2]",matrix[2][2])

#select all the elements of the vector
print("row_vector[all ] is ",row_vector[:])

#select the last elemnt of the vector
print("row_vector[last element is -1  ] is ",row_vector[-1])

#Select first 2 rows and all the columns of  matrix 
print(matrix[:2 ,:])

[  10   15   20   45   34   23 1234]
the matrix is  [[10 20 30]
 [40 50 60]
 [34 45 67]]
row_vector[2] is  15
the 3rd  row and 3rd column is [2][2] 67
row_vector[all ] is  [  10   15   20   45   34   23 1234]
row_vector[last element is -1  ] is  1234
[[10 20 30]
 [40 50 60]]


### Matrix 

In [10]:
matrix = np.array([[10,20,30],[40,50,60],[34,45,67]])
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)# tell the no. of dimwension in the matrix 

(3, 3)
9
2


### Min and Max

In [20]:
#Create a Matrix

matrix = np. array([[10,20,30],[40, 50, 60], [70, 80, 90]])
print(matrix)

#Return the element 
print(np.max(matrix))

##Return the Min element
print(np.min(matrix))

#To find the max element Each coLumn 
print(np.max(matrix, axis=0))

#To find the max element in each row
print(np.max(matrix, axis= 1))

## caluclating the avergae of a matrix 
print(np.mean(matrix))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
90
10
[70 80 90]
[30 60 90]
50.0


### Reshape 


In [26]:
#Create a Matrix

matrix = np. array([[10,20,30],[40, 50, 60], [70, 80, 90]])
print(matrix)
#reshape 
print(matrix.reshape(9,1))

## -1 says as many coln needed for 1 row 
print(matrix.reshape(1,-1))

## it provides 1d array of that length 
print(matrix.reshape(9))

print(matrix.flatten())

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
[[10 20 30 40 50 60 70 80 90]]
[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


### Transpose 

In [27]:
matrix = np. array([[10,20,30],[40, 50, 60], [70, 80, 90]])
print(matrix)
## Transpose of a matrix 
print(matrix.T)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]


### DIagonal

In [29]:
matrix = np. array([[10,20,30],[40, 50, 60], [70, 80, 90]])
print(matrix)
## print the principal diagonal 
print(matrix.diagonal())

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 50 90]


### Dot product

In [31]:
v1=np.array([10,20,30])
v2=np.array([40,50,60])
print(np.dot(v1,v2))

3200


### Addition , Subtraction and Multilication of a matrix 

In [36]:
m1=np.array([[10,20,30],[30,40,50],[65,66,67]])
m2=np.array([[12,22,22],[33,43,54],[62,67,63]])
print(np.add(m1,m2))
print(np.subtract(m1,m2))
## multiplication coln wise 
print(m1*m2)
## multiplicatio row column wise 
print(np.matmul(m1,m2))


[[ 22  42  52]
 [ 63  83 104]
 [127 133 130]]
[[-2 -2  8]
 [-3 -3 -4]
 [ 3 -1  4]]
[[ 120  440  660]
 [ 990 1720 2700]
 [4030 4422 4221]]
[[2640 3090 3190]
 [4780 5730 5970]
 [7112 8757 9215]]


### Creating matrix of zeros and ones 

In [40]:
zeros =np.zeros([4,4])
print(zeros)
ones =np.ones([3,3])
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Generating random values 


In [41]:
print(np.random.randint(0,11,3))

[0 3 8]


In [42]:
print(np.random.normal(1.0,2.0,6))

[-1.5438698  -1.3230708   3.19259744  1.91188285  1.81132899  2.47728041]
